spring:
  datasource:
    url: jdbc:mysql://localhost:3306/candyshop?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate        # OK nếu migration tạo đủ bảng
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    # baseline-on-migrate: true   # CHỈ bật nếu DB đã có sẵn bảng

server:
  port: 8080

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+_CHARS"
    expiration: 3600000
